from __future__ import annotations

import random
from datetime import date


TOPICS = [
    "Operations as code",
    "Small reversible changes",
    "Runbooks for common operations",
    "Playbooks for incident response",
    "Operational readiness reviews",
    "Workload health monitoring",
    "Operations health monitoring",
    "Event response and escalation",
    "Continuous operational improvement",
    "Learning from operational failures",
    "Shared responsibility model",
    "AWS account structure",
    "Centralized identity management",
    "IAM least privilege",
    "Multi-factor authentication",
    "Temporary credentials",
    "Secrets management",
    "Security event detection",
    "Centralized security logging",
    "Vulnerability management",
    "Network protection",
    "Edge protection",
    "Data classification",
    "Encryption at rest",
    "Encryption in transit",
    "Key management",
    "Backup protection",
    "Security incident response",
    "Application security",
    "Security ownership in teams",
    "Service quotas",
    "Network topology planning",
    "Loose coupling",
    "Distributed system interactions",
    "Throttling and load shedding",
    "Horizontal scaling",
    "Change management",
    "Automated recovery",
    "Disaster recovery planning",
    "Recovery objective testing",
    "Architecture selection",
    "Compute selection",
    "Storage selection",
    "Database selection",
    "Caching",
    "Content delivery",
    "Performance metrics",
    "Load testing",
    "Benchmarking",
    "Regular performance review",
    "Cloud financial management",
    "Cost allocation tags",
    "Budget alerts",
    "Cost and usage visibility",
    "Right-sizing resources",
    "Pricing model selection",
    "Demand-based scaling",
    "Removing unused resources",
    "Managed services for cost reduction",
    "Cost optimization over time",
    "Sustainable region selection",
    "Aligning supply with demand",
    "Reducing idle resources",
    "Data lifecycle management",
    "Efficient software design",
    "Efficient hardware selection",
    "Managed services for sustainability",
    "Sustainability metrics",
    "Reducing unnecessary data movement",
    "Sustainability improvement reviews",
]


def select_topic() -> str:
    return random.choice(TOPICS)